"""Tests for reading C2PA Content Credentials.

The fixtures are genuinely signed files, not hand-written JSON:

  * `signed_algorithmic.svg` — signed with a throwaway CA, carrying a
    `c2pa.created` action with an IPTC `digitalSourceType`.
  * `signed_by_stencila.svg` — signed by `stencila credentials sign`, carrying
    the `org.stencila.provenance` graph assertion.
  * `unsigned.svg` — the same artwork with no manifest at all.

Testing against real signatures is the point: the parsing is only useful if it
survives what the actual tools emit.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from figmint.assets import describe, hash_file
from figmint.credentials import (
    ContentCredentials,
    parse_manifest_store,
    parse_stencila_provenance,
    read,
)

FIXTURES = Path(__file__).parent / "fixtures"
EXAMPLES = Path(__file__).parent.parent / "examples"

#: Hash of the artwork before any manifest was embedded.
UNSIGNED_DIGEST = "sha256:ff1f3fef05a1416456a72b25be66d0009780ea2d9e14dd95efc2d5fe3929cb85"


def test_unsigned_file_has_no_credentials():
    assert read(FIXTURES / "unsigned.svg") is None


def test_unsupported_format_is_skipped(tmp_path: Path):
    target = tmp_path / "notes.txt"
    target.write_text("not an image")
    assert read(target) is None


def test_missing_file_does_not_raise(tmp_path: Path):
    assert read(tmp_path / "nope.png") is None


def test_unsigned_fixture_digest_is_the_expected_baseline():
    assert hash_file(FIXTURES / "unsigned.svg") == UNSIGNED_DIGEST


@pytest.fixture(scope="module")
def creds() -> ContentCredentials:
    result = read(FIXTURES / "signed_algorithmic.svg")
    assert result is not None
    return result


@pytest.fixture(scope="module")
def stencila_creds() -> ContentCredentials:
    result = read(FIXTURES / "signed_by_stencila.svg")
    assert result is not None
    return result


@pytest.fixture(scope="module")
def rendered_creds() -> ContentCredentials:
    # Produced by `make components`; committed so the suite does not depend on
    # having the Stencila CLI and a signing identity available.
    result = read(EXAMPLES / "figures" / "schematic.png")
    assert result is not None
    return result


class TestSignedWithSourceType:
    def test_reads_signer_identity(self, creds: ContentCredentials):
        assert creds.signedBy == "figmint test signer"
        assert creds.issuer == "figmint"
        assert creds.signedAt is not None

    def test_reads_the_producing_tool(self, creds: ContentCredentials):
        assert creds.softwareAgent == "matplotlib 3.9.0"
        assert creds.claimGenerator is not None
        assert "figmint-test-plotter" in creds.claimGenerator

    def test_reads_digital_source_type(self, creds: ContentCredentials):
        assert creds.digitalSourceType == "algorithmicMedia"
        assert creds.sourceTypeLabel == "generated by an algorithm"

    def test_algorithmic_media_is_not_flagged_as_ai(self, creds: ContentCredentials):
        # A matplotlib plot is machine-made but not generative AI. Conflating
        # the two would cry wolf on every scripted figure in the project.
        assert creds.machineGenerated is False

    def test_signature_verifies_but_signer_is_untrusted(
        self, creds: ContentCredentials
    ):
        assert creds.validationState == "Valid"
        assert "signingCredential.untrusted" in creds.warnings

    def test_records_the_actions(self, creds: ContentCredentials):
        assert creds.actions == ["c2pa.created"]


class TestSignedByStencila:
    def test_identifies_stencila_as_the_signer(self, stencila_creds: ContentCredentials):
        assert stencila_creds.claimGenerator == "Stencila CLI 2.15.0"
        assert stencila_creds.softwareAgent == "Stencila 2.15.0"

    def test_parses_the_stencila_provenance_graph(self, stencila_creds: ContentCredentials):
        assert stencila_creds.stencila is not None
        assert stencila_creds.stencila.producer == "Stencila 2.15.0"
        assert stencila_creds.stencila.assetType == "image"

    def test_recovers_the_pre_signing_content_digest(
        self, stencila_creds: ContentCredentials
    ):
        # This is what makes staleness survive signing: embedding a manifest
        # changes the file's bytes, but this digest still points at the content
        # figmint originally placed.
        assert stencila_creds.stencila is not None
        assert stencila_creds.stencila.contentDigest == UNSIGNED_DIGEST

    def test_signing_actually_changed_the_file_bytes(self):
        # Guards the premise of the test above — if signing were a no-op the
        # digest recovery would be trivially true and prove nothing.
        assert hash_file(FIXTURES / "signed_by_stencila.svg") != UNSIGNED_DIGEST

    def test_reads_graph_edge_kinds(self, stencila_creds: ContentCredentials):
        assert stencila_creds.stencila is not None
        assert "ConvertedInto" in stencila_creds.stencila.edgeKinds

    def test_credentials_sign_output_currently_fails_c2pa_validation(
        self, stencila_creds: ContentCredentials
    ):
        # `stencila credentials sign` (2.15.0) omits `digitalSourceType` from
        # its `c2pa.created` action, which the C2PA v2 spec requires, so c2pa-rs
        # rejects the manifest outright. Note this is specific to signing a
        # static asset — `stencila render --credentials` sets the field and
        # validates fine (see TestRenderedByStencila).
        #
        # Pinned deliberately: when Stencila fixes this the test will fail, and
        # we should relax it rather than quietly keep expecting a bug.
        assert stencila_creds.validationState == "Invalid"
        assert "assertion.action.malformed" in stencila_creds.warnings


class TestRenderedByStencila:
    """`stencila render doc.smd out.png --credentials`.

    This is the richest provenance path available: Stencila records the source
    document and the execution environment as `inputTo` ingredients, so the
    component arrives carrying the chain that produced it.
    """

    def test_render_output_validates(self, rendered_creds: ContentCredentials):
        # Only the expected untrusted-signer warning, no malformed assertion.
        assert rendered_creds.validationState == "Valid"
        assert "assertion.action.malformed" not in rendered_creds.warnings

    def test_render_sets_a_digital_source_type(
        self, rendered_creds: ContentCredentials
    ):
        assert rendered_creds.digitalSourceType == "digitalCreation"
        assert rendered_creds.machineGenerated is False

    def test_records_execution_as_an_action(
        self, rendered_creds: ContentCredentials
    ):
        assert "org.stencila.executed" in rendered_creds.actions

    def test_source_document_is_recorded_as_an_ingredient(
        self, rendered_creds: ContentCredentials
    ):
        titles = {i.title for i in rendered_creds.ingredients}
        assert "Experimental setup schematic" in titles
        assert all(i.relationship == "inputTo" for i in rendered_creds.ingredients)

    def test_ingredients_carry_their_own_manifests(
        self, rendered_creds: ContentCredentials
    ):
        # This is what makes the provenance chain nest rather than flatten.
        assert all(i.hasManifest for i in rendered_creds.ingredients)

    def test_graph_records_generation_and_use_edges(
        self, rendered_creds: ContentCredentials
    ):
        assert rendered_creds.stencila is not None
        kinds = set(rendered_creds.stencila.edgeKinds)
        assert {"Generated", "UsedBy"} <= kinds


class TestParsing:
    """Unit tests over the normalizers, using minimal synthetic stores."""

    def test_empty_store_yields_empty_credentials(self):
        creds = parse_manifest_store({})
        assert creds.signedBy is None
        assert creds.actions == []

    def test_trained_algorithmic_media_is_flagged_as_ai(self):
        store = {
            "active_manifest": "a",
            "validation_state": "Trusted",
            "manifests": {
                "a": {
                    "assertions": [
                        {
                            "label": "c2pa.actions.v2",
                            "data": {
                                "actions": [
                                    {
                                        "action": "c2pa.created",
                                        "digitalSourceType": "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia",
                                    }
                                ]
                            },
                        }
                    ]
                }
            },
        }
        creds = parse_manifest_store(store)
        assert creds.machineGenerated is True
        assert creds.sourceTypeLabel == "generated by AI"
        assert creds.validationState == "Trusted"

    def test_composite_containing_ai_is_flagged(self):
        for spelling in (
            "compositeWithTrainedAlgorithmicMedia",
            "compositedWithTrainedAlgorithmicMedia",
        ):
            store = {
                "active_manifest": "a",
                "manifests": {
                    "a": {
                        "assertions": [
                            {
                                "label": "c2pa.actions.v2",
                                "data": {
                                    "actions": [
                                        {
                                            "action": "c2pa.placed",
                                            "digitalSourceType": f"http://cv.iptc.org/newscodes/digitalsourcetype/{spelling}",
                                        }
                                    ]
                                },
                            }
                        ]
                    }
                },
            }
            creds = parse_manifest_store(store)
            assert creds.machineGenerated is True, spelling

    def test_creation_action_wins_over_later_actions(self):
        store = {
            "active_manifest": "a",
            "manifests": {
                "a": {
                    "assertions": [
                        {
                            "label": "c2pa.actions.v2",
                            "data": {
                                "actions": [
                                    {
                                        "action": "c2pa.edited",
                                        "digitalSourceType": ".../humanEdits",
                                    },
                                    {
                                        "action": "c2pa.created",
                                        "digitalSourceType": ".../trainedAlgorithmicMedia",
                                    },
                                ]
                            },
                        }
                    ]
                }
            },
        }
        creds = parse_manifest_store(store)
        assert creds.digitalSourceType == "trainedAlgorithmicMedia"

    def test_v1_string_software_agent_is_accepted(self):
        store = {
            "active_manifest": "a",
            "manifests": {
                "a": {
                    "assertions": [
                        {
                            "label": "c2pa.actions",
                            "data": {
                                "actions": [
                                    {
                                        "action": "c2pa.created",
                                        "softwareAgent": "Old Tool 1.0",
                                    }
                                ]
                            },
                        }
                    ]
                }
            },
        }
        assert parse_manifest_store(store).softwareAgent == "Old Tool 1.0"

    def test_component_ingredients_are_parsed(self):
        store = {
            "active_manifest": "a",
            "manifests": {
                "a": {
                    "ingredients": [
                        {
                            "title": "panel-a.svg",
                            "format": "image/svg+xml",
                            "relationship": "componentOf",
                            "instance_id": "xmp:iid:1234",
                            "active_manifest": "urn:c2pa:abcd",
                        }
                    ]
                }
            },
        }
        creds = parse_manifest_store(store)
        assert len(creds.ingredients) == 1
        ingredient = creds.ingredients[0]
        assert ingredient.relationship == "componentOf"
        assert ingredient.title == "panel-a.svg"
        # The ingredient has its own manifest, so the provenance chain nests.
        assert ingredient.hasManifest is True

    def test_unknown_source_type_degrades_gracefully(self):
        store = {
            "active_manifest": "a",
            "manifests": {
                "a": {
                    "assertions": [
                        {
                            "label": "c2pa.actions.v2",
                            "data": {
                                "actions": [
                                    {
                                        "action": "c2pa.created",
                                        "digitalSourceType": ".../somethingNewIn2030",
                                    }
                                ]
                            },
                        }
                    ]
                }
            },
        }
        creds = parse_manifest_store(store)
        assert creds.digitalSourceType == "somethingNewIn2030"
        assert creds.sourceTypeLabel is None
        assert creds.machineGenerated is False

    def test_stencila_graph_without_identifiers_is_safe(self):
        assert parse_stencila_provenance({}).contentDigest is None

    def test_stencila_redaction_count_coerces_to_int(self):
        prov = parse_stencila_provenance(
            {
                "identifiers": [
                    {"propertyId": "org.stencila.redactionCount", "value": "3"}
                ]
            }
        )
        assert prov.redactionCount == 3


class TestAssetIntegration:
    def test_scan_attaches_credentials_to_signed_assets(self):
        asset = describe(FIXTURES / "signed_algorithmic.svg", FIXTURES)
        data = asset.to_dict()
        assert "credentials" in data
        assert data["credentials"]["softwareAgent"] == "matplotlib 3.9.0"
        # The signed agent is promoted into provenance for easy display.
        assert data["provenance"]["signedAgent"] == "matplotlib 3.9.0"

    def test_unsigned_assets_omit_the_credentials_key(self):
        asset = describe(FIXTURES / "unsigned.svg", FIXTURES)
        assert "credentials" not in asset.to_dict()
