"""Reading C2PA Content Credentials from figure components.

When a component is produced by a tool that signs its output — a plotting
script, a generative model, Stencila itself — the artifact carries a
cryptographically signed manifest describing what made it. That is a far better
provenance source than anything figmint could infer, so it is preferred over the
`.prov.yaml` sidecar wherever it is present.

Two questions this answers that a content hash cannot:

  * *Who made this, and with what?* — `claim_generator_info` and the
    `c2pa.created` action's `softwareAgent`.
  * *Was any of it AI-generated?* — the action's `digitalSourceType`. This is the
    direct answer to the "deep fake figure" concern in the design doc.

Reading requires no certificates. Only signing does, which is why this module is
read-only for now.
"""

from __future__ import annotations

import json
import logging
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

#: Formats c2pa-rs can read a manifest from. Note PDF is read-only upstream,
#: which is fine here, and SVG/PNG support full embedding.
CREDENTIALED_SUFFIXES = {
    ".svg",
    ".png",
    ".jpg",
    ".jpeg",
    ".webp",
    ".gif",
    ".tif",
    ".tiff",
    ".avif",
    ".heic",
    ".heif",
    ".pdf",
    ".mp4",
    ".mov",
    ".wav",
    ".mp3",
}

#: IPTC digital source types, keyed by the last segment of the vocabulary URI.
#: Values are (human label, counts as machine-generated).
_SOURCE_TYPES: dict[str, tuple[str, bool]] = {
    "digitalCapture": ("captured digitally", False),
    "computationalCapture": ("computational capture", False),
    "negativeFilm": ("scanned from negative film", False),
    "positiveFilm": ("scanned from positive film", False),
    "print": ("scanned from print", False),
    "humanEdits": ("edited by a human", False),
    "digitalCreation": ("created in software by a human", False),
    "dataDrivenMedia": ("generated from data", False),
    "algorithmicMedia": ("generated by an algorithm", False),
    "algorithmicallyEnhanced": ("algorithmically enhanced", False),
    "screenCapture": ("screen capture", False),
    "virtualRecording": ("virtual recording", False),
    "composite": ("composite of several sources", False),
    "compositeCapture": ("composite of captured sources", False),
    "compositeSynthetic": ("composite of synthetic sources", True),
    "trainedAlgorithmicMedia": ("generated by AI", True),
    "trainedAlgorithmicData": ("AI-generated data", True),
    "compositeWithTrainedAlgorithmicMedia": ("contains AI-generated elements", True),
    # The spec and IPTC have both spellings in circulation; accept either.
    "compositedWithTrainedAlgorithmicMedia": ("contains AI-generated elements", True),
}


@dataclass
class Ingredient:
    """A component asset recorded inside another asset's manifest."""

    title: str | None = None
    format: str | None = None
    #: `parentOf` (edited from), `componentOf` (composited in), `inputTo` (fed to a model).
    relationship: str | None = None
    instanceId: str | None = None  # noqa: N815 - matches the TypeScript model
    #: True when the ingredient carries its own manifest, i.e. the chain nests.
    hasManifest: bool = False  # noqa: N815


#: Stencila embeds a JSON-LD provenance graph under this assertion label.
STENCILA_PROVENANCE = "org.stencila.provenance"


@dataclass
class StencilaProvenance:
    """The `org.stencila.provenance` assertion Stencila writes when signing.

    Stencila embeds a JSON-LD `Graph` — nodes for the asset, the source
    document, and the producing software; edges recording how one became
    another. That is the same knowledge-graph shape figmint wants for composite
    figures, so it is worth reading rather than flattening away.

    The most immediately useful field is `contentDigest`: the hash of the asset
    *before* signing. Embedding a manifest changes the file's bytes, so a signed
    artifact no longer matches the hash figmint recorded at import. This digest
    is what lets staleness detection survive signing.
    """

    #: `sha256:...` of the asset before the manifest was embedded.
    contentDigest: str | None = None  # noqa: N815
    producer: str | None = None
    assetType: str | None = None  # noqa: N815
    #: Stencila's AI-disclosure slot; null when nothing was declared.
    aiDisclosure: Any = None  # noqa: N815
    #: Edge kinds in the graph, e.g. `ConvertedInto`, `DerivedFrom`.
    edgeKinds: list[str] = field(default_factory=list)  # noqa: N815
    redactionCount: int | None = None  # noqa: N815


def _identifiers(entries: Any) -> dict[str, Any]:
    """Flatten a list of schema.org PropertyValue objects into a dict."""
    out: dict[str, Any] = {}
    for entry in entries or []:
        if isinstance(entry, dict) and "propertyId" in entry:
            out[str(entry["propertyId"])] = entry.get("value")
    return out


def parse_stencila_provenance(data: dict[str, Any]) -> StencilaProvenance:
    """Pull the useful fields out of Stencila's provenance graph."""
    props: dict[str, Any] = {}
    ai_disclosure = None
    edge_kinds: list[str] = []

    # Identifiers appear on the graph itself, on each node, and on the evidence
    # attached to each edge. Collect them all; later writes win, which is what
    # we want since edge evidence is the most specific.
    props.update(_identifiers(data.get("identifiers")))
    for node in data.get("nodes") or []:
        inner = node.get("node") if isinstance(node, dict) else None
        if isinstance(inner, dict):
            props.update(_identifiers(inner.get("identifiers")))
    for edge in data.get("edges") or []:
        if not isinstance(edge, dict):
            continue
        kind = edge.get("kind")
        if kind:
            edge_kinds.append(str(kind))
        for evidence in edge.get("evidence") or []:
            details = evidence.get("details") if isinstance(evidence, dict) else None
            if not isinstance(details, dict):
                continue
            props.update(_identifiers(details.get("identifiers")))
            if details.get("aiDisclosure") is not None:
                ai_disclosure = details["aiDisclosure"]

    producer_name = props.get("org.stencila.producer.name")
    producer_version = props.get("org.stencila.producer.version")
    producer = None
    if producer_name:
        producer = (
            f"{producer_name} {producer_version}" if producer_version else str(producer_name)
        )

    redactions = props.get("org.stencila.redactionCount")
    try:
        redaction_count = int(redactions) if redactions is not None else None
    except (TypeError, ValueError):
        redaction_count = None

    return StencilaProvenance(
        contentDigest=props.get("org.stencila.contentDigest"),
        producer=producer,
        assetType=props.get("org.stencila.assetType"),
        aiDisclosure=ai_disclosure,
        edgeKinds=edge_kinds,
        redactionCount=redaction_count,
    )


@dataclass
class ContentCredentials:
    """Normalized view of an asset's C2PA manifest store."""

    #: `Trusted`, `Valid` (cryptographically sound but signer not in a trust
    #: list), or `Invalid` (tampered, or the signature does not verify).
    validationState: str | None = None  # noqa: N815
    #: Common name on the signing certificate.
    signedBy: str | None = None  # noqa: N815
    issuer: str | None = None
    signedAt: str | None = None  # noqa: N815
    #: Tool that wrote the claim, e.g. "Stencila 2.15.0".
    claimGenerator: str | None = None  # noqa: N815
    #: Tool named in the creation action, e.g. "matplotlib 3.9.0".
    softwareAgent: str | None = None  # noqa: N815
    #: Last URI segment of the IPTC digital source type.
    digitalSourceType: str | None = None  # noqa: N815
    sourceTypeLabel: str | None = None  # noqa: N815
    #: True when the source type indicates generative-AI involvement.
    machineGenerated: bool = False  # noqa: N815
    actions: list[str] = field(default_factory=list)
    ingredients: list[Ingredient] = field(default_factory=list)
    #: Non-fatal validation codes, e.g. `signingCredential.untrusted`.
    warnings: list[str] = field(default_factory=list)
    #: Present when the asset was signed by Stencila.
    stencila: StencilaProvenance | None = None

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        return {k: v for k, v in data.items() if v not in (None, [], False)}


def _join_name(entry: dict[str, Any]) -> str | None:
    name = entry.get("name")
    if not name:
        return None
    version = entry.get("version")
    return f"{name} {version}" if version else str(name)


def _parse_actions(assertions: list[dict[str, Any]]) -> dict[str, Any]:
    """Pull the interesting bits out of `c2pa.actions` / `c2pa.actions.v2`."""
    names: list[str] = []
    software_agent: str | None = None
    source_type: str | None = None

    for assertion in assertions:
        label = assertion.get("label", "")
        if not label.startswith("c2pa.actions"):
            continue
        for action in assertion.get("data", {}).get("actions", []) or []:
            name = action.get("action")
            if name:
                names.append(name)
            agent = action.get("softwareAgent")
            if software_agent is None and agent:
                # v2 uses an object; v1 allowed a bare string.
                software_agent = (
                    _join_name(agent) if isinstance(agent, dict) else str(agent)
                )
            raw = action.get("digitalSourceType")
            # Prefer the type attached to a creation action; otherwise take the
            # first one seen, so an edit action still tells us something.
            if raw and (source_type is None or name == "c2pa.created"):
                source_type = str(raw).rsplit("/", 1)[-1]

    return {
        "actions": names,
        "softwareAgent": software_agent,
        "digitalSourceType": source_type,
    }


def _parse_ingredients(raw: list[dict[str, Any]] | None) -> list[Ingredient]:
    out: list[Ingredient] = []
    for entry in raw or []:
        out.append(
            Ingredient(
                title=entry.get("title") or entry.get("dc:title"),
                format=entry.get("format") or entry.get("dc:format"),
                relationship=entry.get("relationship"),
                instanceId=entry.get("instance_id") or entry.get("instanceID"),
                # Either an embedded manifest or a pointer to one means this
                # ingredient has provenance of its own worth following.
                hasManifest=bool(
                    entry.get("active_manifest") or entry.get("c2pa_manifest")
                ),
            )
        )
    return out


def parse_manifest_store(store: dict[str, Any]) -> ContentCredentials:
    """Normalize a c2pa manifest-store JSON document.

    Split out from :func:`read` so it can be tested against captured fixtures
    without needing to sign anything.
    """
    active_label = store.get("active_manifest")
    manifests = store.get("manifests") or {}
    active = manifests.get(active_label, {}) if active_label else {}

    generator = None
    generators = active.get("claim_generator_info") or []
    if generators:
        generator = _join_name(generators[0])

    signature = active.get("signature_info") or {}
    parsed = _parse_actions(active.get("assertions") or [])

    source_type = parsed["digitalSourceType"]
    label, machine = _SOURCE_TYPES.get(source_type or "", (None, False))

    # Surface only genuinely non-fatal codes here; a hard failure shows up in
    # validation_state instead.
    warnings = [
        entry.get("code", "")
        for entry in store.get("validation_status") or []
        if entry.get("code")
    ]

    stencila = None
    for assertion in active.get("assertions") or []:
        if assertion.get("label") == STENCILA_PROVENANCE:
            data = assertion.get("data")
            if isinstance(data, dict):
                stencila = parse_stencila_provenance(data)
            break

    return ContentCredentials(
        stencila=stencila,
        validationState=store.get("validation_state"),
        signedBy=signature.get("common_name"),
        issuer=signature.get("issuer"),
        signedAt=signature.get("time"),
        claimGenerator=generator,
        softwareAgent=parsed["softwareAgent"],
        digitalSourceType=source_type,
        sourceTypeLabel=label,
        machineGenerated=machine,
        actions=parsed["actions"],
        ingredients=_parse_ingredients(active.get("ingredients")),
        warnings=warnings,
    )


def read(path: Path) -> ContentCredentials | None:
    """Read Content Credentials from a file, or None when it has none.

    Never raises: an unsigned or unreadable file is the common case, not an
    error, and a failure here must not take down the directory scan.
    """
    if path.suffix.lower() not in CREDENTIALED_SUFFIXES:
        return None
    try:
        from c2pa import Reader
    except ImportError:  # pragma: no cover - c2pa is a hard dependency today
        logger.debug("c2pa not installed; skipping credentials for %s", path)
        return None

    try:
        with Reader(str(path)) as reader:
            store = json.loads(reader.json())
    except Exception:  # noqa: BLE001 - the SDK raises many distinct error types
        # Overwhelmingly this means "no manifest found", which is normal.
        logger.debug("no readable credentials in %s", path, exc_info=True)
        return None

    if not store.get("active_manifest"):
        return None
    return parse_manifest_store(store)
