"""How well do we know where a component came from — and is that good enough?

The problem this solves: nothing stops someone dropping `screenshot.png` into the
figures directory and placing it in a published figure. Six months later nobody
can say what it shows, where it came from, or whether it was generated by a
model. A composite figure is only as trustworthy as its least accountable panel.

figmint does not answer this by forbidding imports — researchers legitimately use
micrographs, photographs, and diagrams drawn elsewhere. It answers it by
requiring that an imported component be *identified*: if you cannot point at what
produced a file, you must at least say where you got it.

Five levels, worst to best:

    unidentified  a file that simply appeared. Nothing is known.
    declared      imported, but with a stated origin — a URL, DOI, or citation.
    generated     a sidecar names a script or command that produced it.
    reproducible  a Calkit pipeline stage declares this exact file as an output.
    signed        carries valid C2PA Content Credentials naming its producer.

The step from `generated` to `reproducible` is the important one. "Produced by
`scripts/plot.py`" written in a sidecar is a self-assertion — nothing checks it,
and nothing stops it being wrong or stale. "Stage `plot-cp` in `calkit.yaml`
declares this path as an output" is *verifiable*, without running anything, and
it carries Calkit's environment locks and DVC hashes behind it. That is the
"unambiguous proof of work" an imported component needs.

A project sets the minimum it will accept in `figmint.toml`. The default is
`declared`, which blocks the real failure case — an anonymous file — without
getting in the way of a project that has not adopted a pipeline yet.

A caveat worth stating: `signed` and `reproducible` are not really comparable.
Signing answers *who made this and has it been altered*; a pipeline stage answers
*can I make it again*. For a research figure the second is often the more
valuable property, so a project that cares specifically about reproducibility
should set `require = "reproducible"` rather than assuming the top of the ladder
implies it. Collapsing two orthogonal qualities into one order is a simplification
that works for the common case and should be revisited if it starts to chafe.
"""

from __future__ import annotations

import tomllib
from dataclasses import dataclass
from enum import IntEnum
from pathlib import Path
from typing import Any

CONFIG_NAME = "figmint.toml"


class Level(IntEnum):
    """Provenance quality. Ordered, so policy is a comparison."""

    UNIDENTIFIED = 0
    DECLARED = 1
    GENERATED = 2
    REPRODUCIBLE = 3
    SIGNED = 4

    @property
    def slug(self) -> str:
        return self.name.lower()

    @classmethod
    def parse(cls, value: str) -> "Level":
        try:
            return cls[value.strip().upper()]
        except KeyError as exc:
            valid = ", ".join(level.slug for level in cls)
            raise ValueError(
                f"unknown provenance level {value!r}; expected one of {valid}"
            ) from exc


LEVEL_LABEL: dict[Level, str] = {
    Level.UNIDENTIFIED: "no stated origin",
    Level.DECLARED: "origin declared",
    Level.GENERATED: "generated in project",
    Level.REPRODUCIBLE: "pipeline output",
    Level.SIGNED: "signed credentials",
}

#: Sidecar keys that count as stating where an imported file came from.
ORIGIN_KEYS = ("importedFrom", "url", "doi", "citation", "derivedFrom")

#: Sidecar keys that count as naming what produced a file in this project.
GENERATOR_KEYS = ("generatedBy", "command")


@dataclass(frozen=True)
class Policy:
    """What a project will accept, and how strictly."""

    require: Level = Level.DECLARED
    #: When False a violation is reported but not blocked, which is the sane
    #: setting for adopting this on a project that already has loose figures.
    enforce: bool = True

    def permits(self, level: Level) -> bool:
        return level >= self.require

    def to_dict(self) -> dict[str, Any]:
        return {"require": self.require.slug, "enforce": self.enforce}


DEFAULT_POLICY = Policy()


def load_policy(root: Path) -> Policy:
    """Read `[provenance]` from `figmint.toml`, falling back to the default.

    A malformed config raises rather than silently reverting to the default —
    quietly ignoring a policy someone wrote down would be the worst outcome for
    a feature whose whole job is enforcement.
    """
    config = root / CONFIG_NAME
    if not config.exists():
        return DEFAULT_POLICY

    with config.open("rb") as handle:
        data = tomllib.load(handle)

    section = data.get("provenance")
    if not isinstance(section, dict):
        return DEFAULT_POLICY

    require = section.get("require", DEFAULT_POLICY.require.slug)
    enforce = section.get("enforce", DEFAULT_POLICY.enforce)
    if not isinstance(enforce, bool):
        raise ValueError(f"{CONFIG_NAME}: provenance.enforce must be true or false")

    return Policy(require=Level.parse(str(require)), enforce=enforce)


@dataclass
class Assessment:
    """The provenance level of one component, and why."""

    level: Level
    reason: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "level": self.level.slug,
            "label": LEVEL_LABEL[self.level],
            "reason": self.reason,
        }


def assess(
    provenance: dict[str, Any] | None,
    credentials: dict[str, Any] | None,
    stage: Any = None,
) -> Assessment:
    """Classify a component from its provenance, credentials, and pipeline stage.

    Takes plain dicts rather than typed objects so it works identically on a
    freshly-scanned asset and on a source recorded in a saved document. `stage`
    is a `calkit.Stage` when the file is a declared pipeline output.
    """
    provenance = provenance or {}
    credentials = credentials or {}

    # Signed beats everything — but only if the signature actually verifies.
    # An `Invalid` manifest means the file was altered after signing, which is
    # worse than no claim at all, so it is explicitly not counted as signed.
    state = credentials.get("validationState")
    if credentials and state in ("Valid", "Trusted"):
        agent = credentials.get("softwareAgent") or credentials.get("claimGenerator")
        detail = f" naming {agent}" if agent else ""
        return Assessment(
            Level.SIGNED, f"C2PA credentials verify ({state}){detail}"
        )

    # A declared pipeline output outranks a sidecar's claim to the same effect,
    # because this one can be checked rather than taken on trust.
    #
    # But only while the stage is actually current. If its dependencies have
    # changed since it last ran, the file on disk is the output of a version of
    # the stage that no longer exists, and "I can make this again" is false of
    # the thing in front of you. That drops it to the same standing as a sidecar
    # claim: something names what produced it, but nothing verifies it.
    if stage is not None:
        if getattr(stage, "verified", True):
            return Assessment(Level.REPRODUCIBLE, stage.describe())
        return Assessment(Level.GENERATED, stage.describe_staleness())

    for key in GENERATOR_KEYS:
        if provenance.get(key):
            return Assessment(
                Level.GENERATED,
                f"sidecar claims `{provenance[key]}` produced it, but no "
                f"pipeline stage declares it as an output",
            )

    for key in ORIGIN_KEYS:
        value = provenance.get(key)
        if value:
            shown = value[0] if isinstance(value, list) and value else value
            return Assessment(Level.DECLARED, f"origin declared via `{key}`: {shown}")

    if state == "Invalid":
        return Assessment(
            Level.UNIDENTIFIED,
            "C2PA credentials present but do not verify — the file was altered "
            "after signing",
        )

    return Assessment(
        Level.UNIDENTIFIED,
        "no credentials, no generating command, and no declared origin",
    )


def explain_fix(level: Level, path: str, require: Level = Level.DECLARED) -> str:
    """A concrete next step for a component that fails policy."""
    if require >= Level.REPRODUCIBLE and level < Level.REPRODUCIBLE:
        return (
            f"make it a pipeline output:  calkit xr <script that writes {path}>"
            f"  — or, if it is genuinely external, add a stage that fetches it"
        )
    if level is Level.UNIDENTIFIED:
        return (
            f"declare where it came from:  figmint import {path} "
            f"--from '<url or DOI>'"
        )
    return "have the producing tool sign its output, e.g. `stencila render --credentials`"
