"""The provenance record: `figmint.toml`.

Everything figmint knows about a project lives in one file at its root. An
output is recorded with the hash of its bytes, the hashes of every input it was
derived from — the environment lock file included — and the command that
produced it. That is the whole model. Freshness is then a comparison, and a
composite figure is just an output whose inputs happen to be other artifacts.

Two properties are load-bearing.

**It is evidence.** The hashes are the reason a claim like "this figure came
from that script under that environment" can be checked rather than believed.
A file that is edited by hand, or by an agent tidying up a diff, stops being
evidence and becomes decoration — and it looks exactly the same. Hence the
header: the warning is not decoration itself, it is the only thing standing
between a reader and a forged chain of custody.

**It is rewritten wholesale.** figmint owns the file, so there is no attempt to
preserve unknown keys or user formatting. Anything a human put here is lost on
the next `figmint run`, which is the correct behavior for a record nobody
should be writing by hand.
"""

from __future__ import annotations

import hashlib
import tomllib
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .origins import Author

STORE_NAME = "figmint.toml"

#: Written at the top of every `figmint.toml`. Addressed to agents explicitly,
#: because an agent is the reader most likely to "fix" a hash mismatch by
#: editing the hash — the one repair that destroys exactly what the file is for.
HEADER = """\
# ─────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED BY FIGMINT — DO NOT EDIT.
#
# This file is the provenance record for this project: which artifact came from
# which inputs, under which environment, and the SHA256 of every one of them.
# It is written by `figmint run` and read by `figmint status`.
#
# NOTE TO AI AGENTS AND OTHER AUTOMATED TOOLS:
#
#   Do not edit this file to resolve an error, silence a warning, or make a
#   check pass. If `figmint status` reports an artifact as stale, the artifact
#   is stale — the fix is to regenerate it, not to update the hash recorded
#   here.
#
#   These hashes are evidence. In a scientific project, altering them to match
#   files they do not describe is falsifying that evidence, whether or not
#   anyone intended it that way. A record that has been "tidied" is
#   indistinguishable from one that has been forged, which is why neither is
#   acceptable.
#
#   If something here looks wrong, say so. Do not correct it.
# ─────────────────────────────────────────────────────────────────────────────
"""

CHUNK = 1 << 20


def hash_file(path: Path) -> str:
    """SHA256 of a file's bytes, prefixed so the algorithm is never implicit."""
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        while chunk := handle.read(CHUNK):
            digest.update(chunk)
    return f"sha256:{digest.hexdigest()}"


def find_root(start: Path) -> Path | None:
    """Walk upward looking for a project that already has a record."""
    start = Path(start).resolve()
    for directory in [start, *start.parents]:
        if (directory / STORE_NAME).is_file():
            return directory
    return None


#: Files that mark the top of a project, tried in this order after an existing
#: record. The environment manifest comes before version control on purpose: a
#: repository can hold several self-contained projects — an example beside the
#: tool it demonstrates — and each of those has its own environment and so its
#: own provenance. Recording them all against the outer `.git` would put one
#: project's artifacts in another's record.
MARKERS = (
    "pyproject.toml",
    "pixi.toml",
    "Cargo.toml",
    "package.json",
    "flake.nix",
    "calkit.yaml",
)


def project_root(start: Path) -> Path:
    """Where a record would live for this path."""
    start = Path(start).resolve()
    existing = find_root(start)
    if existing:
        return existing

    base = start if start.is_dir() else start.parent
    for directory in [base, *base.parents]:
        if any((directory / name).is_file() for name in MARKERS):
            return directory
    for directory in [base, *base.parents]:
        if (directory / ".git").exists():
            return directory
    return base


@dataclass
class Input:
    """One thing an output was derived from."""

    path: str
    hash: str
    #: `environment` marks a lock file. Worth distinguishing because it answers
    #: a different question — not "what did this depend on" but "what was it
    #: computed with" — and because it is the input a reader is least likely to
    #: have thought about.
    kind: str = "file"

    def to_dict(self) -> dict[str, Any]:
        return {"path": self.path, "hash": self.hash, "kind": self.kind}

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Input":
        return cls(
            path=str(data.get("path", "")),
            hash=str(data.get("hash", "")),
            kind=str(data.get("kind", "file")),
        )


@dataclass
class Artifact:
    """One recorded output and everything it came from."""

    path: str
    hash: str
    inputs: list[Input] = field(default_factory=list)
    command: str | None = None
    recorded: str | None = None
    #: How it was produced: `run`, `drawio-export`, `gimp-export`, `primary`
    #: for something figmint did not make, or `authored` for something made by
    #: hand *from* recorded inputs — a `.drawio` canvas is assembled from
    #: tracked panels but arranged by people and agents, so it has a derivation
    #: chain and an author list at the same time.
    kind: str = "run"
    #: For a primary artifact: what kind of claim its origin is —
    #: `attested`, `doi`, `git`, `calkit`.
    origin_kind: str | None = None
    #: The claim itself.
    origin: str | None = None
    #: Revision, for the location forms.
    origin_revision: str | None = None
    #: Everyone who made a declared artifact, in order. An artifact rarely has
    #: exactly one author and code almost never does, so this is a list rather
    #: than a name, and each entry records whether it is a person or a tool.
    authors: list["Author"] = field(default_factory=list)
    #: True when a C2PA manifest was embedded. Signing rewrites the file, so the
    #: hash above is of the *signed* bytes — the ones on disk.
    signed: bool = False

    def origin_description(self) -> str:
        """The declared origin as a reader should see it.

        Built here rather than in `origins` because the record is what survives:
        a stored artifact has three plain fields, and rendering them must not
        depend on being able to reconstruct the `Origin` that wrote them.
        """
        if not self.origin_kind:
            return ""
        if self.origin_kind == "attested":
            names = [a.describe() for a in self.authors] or [
                self.origin or "?"
            ]
            if len(names) > 1:
                joined = f"{', '.join(names[:-1])} and {names[-1]}"
            else:
                joined = names[0]
            return f"created by {joined}"
        if self.origin_kind == "doi":
            return f"doi:{self.origin}"
        return f"{self.origin_kind}:{self.origin}@{self.origin_revision}"

    def to_dict(self) -> dict[str, Any]:
        out: dict[str, Any] = {"hash": self.hash, "kind": self.kind}
        if self.command:
            out["command"] = self.command
        if self.recorded:
            out["recorded"] = self.recorded
        if self.signed:
            out["signed"] = True
        if self.origin or self.origin_kind:
            out["origin_kind"] = self.origin_kind
            if self.origin:
                out["origin"] = self.origin
            if self.origin_revision:
                out["origin_revision"] = self.origin_revision
        if self.authors:
            out["authors"] = [a.to_dict() for a in self.authors]
        out["inputs"] = [i.to_dict() for i in self.inputs]
        return out

    @classmethod
    def from_dict(cls, path: str, data: dict[str, Any]) -> "Artifact":
        return cls(
            path=path,
            hash=str(data.get("hash", "")),
            inputs=[Input.from_dict(i) for i in data.get("inputs", []) or []],
            command=data.get("command"),
            recorded=data.get("recorded"),
            kind=_KIND_ALIASES.get(
                str(data.get("kind", "run")), str(data.get("kind", "run"))
            ),
            signed=bool(data.get("signed", False)),
            origin_kind=data.get("origin_kind"),
            origin=data.get("origin"),
            origin_revision=data.get("origin_revision"),
            authors=_read_authors(data),
        )


def _read_authors(data: dict[str, Any]) -> list["Author"]:
    """Author list, tolerating records written before it existed.

    The older shape put a single name in `origin` and a single tool in
    `origin_ai`. Reading it forward rather than ignoring it matters more here
    than tidiness would: silently dropping an author from a record whose whole
    purpose is accountability is the one failure this file must not have.
    """
    from .origins import Author

    listed = data.get("authors") or []
    if listed:
        return [
            Author(
                name=str(a.get("name", "")),
                kind=str(a.get("kind", "person")),
            )
            for a in listed
            if a.get("name")
        ]

    if data.get("origin_kind") != "attested":
        return []
    authors = []
    if data.get("origin"):
        authors.append(Author(str(data["origin"]), "person"))
    if data.get("origin_ai"):
        authors.append(Author(str(data["origin_ai"]), "ai"))
    return authors


#: Kinds that were renamed. Mapped on read so an existing record keeps working:
#: `drawio-import` described the command that happened to make the file, but
#: what matters about a `.drawio` is that it was arranged by hand from recorded
#: inputs, which is true however it got there.
_KIND_ALIASES = {"drawio-import": "authored"}


class StoreError(RuntimeError):
    """Raised when the record cannot be read."""


@dataclass
class Store:
    """A project's provenance record, in memory."""

    root: Path
    artifacts: dict[str, Artifact] = field(default_factory=dict)

    @property
    def path(self) -> Path:
        return self.root / STORE_NAME

    # -- reading ----------------------------------------------------------

    @classmethod
    def load(cls, root: Path) -> "Store":
        root = Path(root).resolve()
        store = cls(root=root)
        path = root / STORE_NAME
        if not path.is_file():
            return store
        try:
            with path.open("rb") as handle:
                data = tomllib.load(handle)
        except (OSError, tomllib.TOMLDecodeError) as exc:
            raise StoreError(f"{path}: {exc}") from exc

        for key, value in (data.get("artifact") or {}).items():
            if isinstance(value, dict):
                store.artifacts[key] = Artifact.from_dict(key, value)
        return store

    @classmethod
    def for_path(cls, path: Path) -> "Store":
        """Load the record governing this path."""
        return cls.load(project_root(Path(path)))

    def relative(self, path: Path) -> str:
        """A path as the record spells it: relative to the root, posix."""
        resolved = Path(path).resolve()
        try:
            return resolved.relative_to(self.root).as_posix()
        except ValueError:
            # Outside the project. Recorded absolute rather than dropped: an
            # input that lives elsewhere is still an input, and silently
            # omitting it would make the chain look complete when it is not.
            return resolved.as_posix()

    def get(self, path: Path | str) -> Artifact | None:
        key = path if isinstance(path, str) else self.relative(path)
        return self.artifacts.get(key)

    # -- writing ----------------------------------------------------------

    def record(self, artifact: Artifact) -> None:
        """Store an artifact, carrying its declaration forward.

        Every writer builds a fresh `Artifact` describing what it just did, and
        none of them know or care who declared the file. Without this, importing
        a panel into a diagram somebody had signed their name to would silently
        drop the authorship — the record would lose the one thing about that
        file nothing else can reconstruct.

        Merged here rather than at each call site so a writer added later cannot
        get it wrong.
        """
        previous = self.artifacts.get(artifact.path)
        if previous is not None:
            if not artifact.authors:
                artifact.authors = list(previous.authors)
            if not artifact.origin_kind:
                artifact.origin_kind = previous.origin_kind
                artifact.origin = previous.origin
                artifact.origin_revision = previous.origin_revision

        artifact.recorded = datetime.now(timezone.utc).isoformat(
            timespec="seconds"
        )
        self.artifacts[artifact.path] = artifact

    def save(self) -> None:
        """Write the record, header first.

        Serialized by hand rather than through a TOML writer, for one reason:
        the header has to be there, and no writer emits comments. Sorted so a
        diff shows what changed rather than what moved.
        """
        lines = [HEADER]
        for key in sorted(self.artifacts):
            artifact = self.artifacts[key]
            lines.append(f"\n[artifact.{_key(key)}]")
            lines.append(f"hash = {_string(artifact.hash)}")
            lines.append(f"kind = {_string(artifact.kind)}")
            if artifact.command:
                lines.append(f"command = {_string(artifact.command)}")
            if artifact.recorded:
                lines.append(f"recorded = {_string(artifact.recorded)}")
            if artifact.signed:
                lines.append("signed = true")
            if artifact.origin or artifact.origin_kind:
                lines.append(
                    f"origin_kind = {_string(artifact.origin_kind or '')}"
                )
                if artifact.origin:
                    lines.append(f"origin = {_string(artifact.origin)}")
                if artifact.origin_revision:
                    lines.append(
                        f"origin_revision = {_string(artifact.origin_revision)}"
                    )
            for author in artifact.authors:
                lines.append(f"\n[[artifact.{_key(key)}.authors]]")
                lines.append(f"name = {_string(author.name)}")
                lines.append(f"kind = {_string(author.kind)}")
            for item in artifact.inputs:
                lines.append(f"\n[[artifact.{_key(key)}.inputs]]")
                lines.append(f"path = {_string(item.path)}")
                lines.append(f"hash = {_string(item.hash)}")
                lines.append(f"kind = {_string(item.kind)}")

        self.path.parent.mkdir(parents=True, exist_ok=True)
        # Written via a temporary file so an interrupted write cannot leave a
        # truncated record, which would read as "no provenance" rather than as
        # a problem.
        temporary = self.path.with_name(self.path.name + ".tmp")
        temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
        temporary.replace(self.path)


def _key(value: str) -> str:
    """A TOML bare key, or a quoted one. Paths need quoting."""
    if value and all(c.isalnum() or c in "-_" for c in value):
        return value
    return _string(value)


def _string(value: str) -> str:
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
