import { useEffect, useState } from 'react'
import { useEditor } from '../state/store'
import { assetUrl } from '../io/api'
import { sourceStatus, usedSourceKeys } from '../model/document'
import { CredentialBadges, CredentialDetail } from './Credentials'
import type { Asset, SourceStatus } from '../model/types'

/**
 * Left rail: the local figure directory, plus the provenance ledger for sources
 * already used in this document.
 *
 * The provenance section is the point of the whole application — it answers
 * "where did this panel come from, and has it changed since I placed it?"
 */

const STATUS_LABEL: Record<SourceStatus, string> = {
  ok: 'up to date',
  stale: 'source changed',
  missing: 'file not found',
  unknown: 'no recorded hash',
}

export function AssetPanel() {
  const assets = useEditor((s) => s.assets)
  const assetsByPath = useEditor((s) => s.assetsByPath)
  const assetError = useEditor((s) => s.assetError)
  const loadAssets = useEditor((s) => s.loadAssets)
  const insertAsset = useEditor((s) => s.insertAsset)
  const relinkSource = useEditor((s) => s.relinkSource)
  const doc = useEditor((s) => s.doc)
  const [filter, setFilter] = useState('')

  useEffect(() => {
    void loadAssets()
  }, [loadAssets])

  const visible = assets.filter((a) =>
    a.path.toLowerCase().includes(filter.toLowerCase()),
  )
  const usedKeys = usedSourceKeys(doc)

  return (
    <aside className="panel panel-left">
      <header className="panel-header">
        <h2>Figures</h2>
        <button
          className="btn-ghost"
          onClick={() => void loadAssets()}
          title="Re-scan the figure directory and re-hash files"
        >
          Rescan
        </button>
      </header>

      {assetError && (
        <p className="notice notice-warn">
          {assetError}
          <br />
          <small>
            The canvas still works; you just can't browse or insert local files.
          </small>
        </p>
      )}

      <input
        className="input"
        placeholder="Filter by path…"
        value={filter}
        onChange={(e) => setFilter(e.target.value)}
      />

      <div className="asset-grid">
        {visible.map((asset) => (
          <AssetTile
            key={asset.path}
            asset={asset}
            onInsert={() => insertAsset(asset)}
          />
        ))}
        {visible.length === 0 && !assetError && (
          <p className="muted">No figures found.</p>
        )}
      </div>

      <header className="panel-header">
        <h2>Provenance</h2>
      </header>
      <div className="source-list">
        {usedKeys.length === 0 && (
          <p className="muted">No sources placed yet.</p>
        )}
        {usedKeys.map((key) => {
          const source = doc.sources[key]
          const status = sourceStatus(source, assetsByPath)
          const live = assetsByPath.get(source.path)
          return (
            <div key={key} className={`source-row source-${status}`}>
              <div className="source-head">
                <code>{key}</code>
                <span className={`badge badge-${status}`}>
                  {STATUS_LABEL[status]}
                </span>
              </div>
              <div className="source-path" title={source.path}>
                {source.path}
              </div>
              {/*
                Prefer the live credentials from the last scan over the copy
                recorded at import: if a file was re-signed, or lost its
                manifest, that is exactly what you need to see.
              */}
              {(live?.credentials ?? source.credentials) && (
                <>
                  <CredentialBadges
                    credentials={live?.credentials ?? source.credentials!}
                  />
                  <CredentialDetail
                    credentials={live?.credentials ?? source.credentials!}
                  />
                </>
              )}
              {source.provenance?.generatedBy && (
                <div className="muted small">
                  generated by <code>{source.provenance.generatedBy}</code>
                </div>
              )}
              {source.provenance?.importedAt && (
                <div className="muted small">
                  placed {source.provenance.importedAt.slice(0, 10)}
                </div>
              )}
              {status === 'stale' && live && (
                <button
                  className="btn-small"
                  onClick={() => relinkSource(key, live)}
                >
                  Accept new version
                </button>
              )}
            </div>
          )
        })}
      </div>
    </aside>
  )
}

function AssetTile({
  asset,
  onInsert,
}: {
  asset: Asset
  onInsert: () => void
}) {
  return (
    <button
      className="asset-tile"
      draggable
      onDragStart={(e) => {
        e.dataTransfer.setData(
          'application/x-figmint-asset',
          JSON.stringify(asset),
        )
        e.dataTransfer.effectAllowed = 'copy'
      }}
      onDoubleClick={onInsert}
      onClick={onInsert}
      title={`${asset.path}\n${asset.hash}`}
    >
      <div className="asset-thumb">
        <img src={assetUrl(asset.path)} alt={asset.name} loading="lazy" />
        {asset.credentials && (
          <span
            className={
              asset.credentials.machineGenerated
                ? 'thumb-mark thumb-ai'
                : 'thumb-mark'
            }
            title={
              asset.credentials.machineGenerated
                ? `Content Credentials: ${asset.credentials.sourceTypeLabel}`
                : 'Has Content Credentials'
            }
          >
            {asset.credentials.machineGenerated ? 'AI' : 'cr'}
          </span>
        )}
      </div>
      <span className="asset-name">{asset.name}</span>
    </button>
  )
}
